# Generated by Django 4.2.11 on 2024-03-17 20:52

from django.db import migrations, models
import image_processing.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(upload_to=image_processing.models.get_upload_path)),
            ],
        ),
    ]
